import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Coffo | Coffee House",
    description: "Generated by create next app",
  };

export default function CoffeeHouseLayout({children}: {children: React.ReactNode}) {
    return (
        <section>
            {children}
        </section>
    );
}